[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mosaicworkflow"
version = "0.0.1"
description = "Greenland Ice Mapping Project (GrIMP) workflow programs"
authors = [
    { name = "Ian Joughin", email = "irj@uw.edu" }
]
license = { text = "MIT" }
readme = "README.md"
keywords = ["SAR", "NISAR"]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["mosaicworkflow"]
script-files = ["scripts/greptops", "scripts/greptopsmonth", "scripts/greptopsmonthuw", "scripts/greptopsuw"]

[project.urls]
Homepage = "https://github.com/fastice/mosaicworkflow"
Repository = "https://github.com/fastice/mosaicworkflow"

[project.scripts]
checkvelsize = "mosaicworkflow.checkvelsize:main"
"checkvelsize.py" = "mosaicworkflow.checkvelsize:main"
grepdate = "mosaicworkflow.grepdate:main"
"grepdate.py" = "mosaicworkflow.grepdate:main"
grepnisar = "mosaicworkflow.grepnisar:main"
"grepnisar.py" = "mosaicworkflow.grepnisar:main"
makeimagemosaics = "mosaicworkflow.makeimagemosaics:main"
makevelnoclean = "mosaicworkflow.makevelnoclean:main"
"makevelnoclean.py" = "mosaicworkflow.makevelnoclean:main"
makemosaic = "mosaicworkflow.makemosaic:main"
prepareTSXrelease = "mosaicworkflow.prepareTSXrelease:main"
setupimagemosaic = "mosaicworkflow.setupimagemosaic:main"
setupquarters = "mosaicworkflow.setupquarters:main"
simoffsets = "mosaicworkflow.simoffsets:main"
"simoffsets.py" = "mosaicworkflow.simoffsets:main"
refreshties = "mosaicworkflow.refreshties:main"
maketies = "mosaicworkflow.maketies:main"
makeframetie = "mosaicworkflow.makeframetie:main"
setuptopstie = "mosaicworkflow.setuptopstie:main"
"refreshties.py" = "mosaicworkflow.refreshties:main"
"maketies.py" = "mosaicworkflow.maketies:main"
"makeframetie.py" = "mosaicworkflow.makeframetie:main"
"setuptopstie.py" = "mosaicworkflow.setuptopstie:main"
velocityStats = "mosaicworkflow.velocityStats:main"
"velocityStats.py" = "mosaicworkflow.velocityStats:main"
initRAReference = "mosaicworkflow.initRAReference:main"
"initRAReference.py" = "mosaicworkflow.initRAReference:main"
makevelstatsregions = "mosaicworkflow.makevelstatsregions:main"
"makevelstatsregions.py" = "mosaicworkflow.makevelstatsregions:main"
autoclean = "mosaicworkflow.autoclean:main"
"autoclean.py" = "mosaicworkflow.autoclean:main"
autocleanNISAR = "mosaicworkflow.autocleanNISAR:main"
"autocleanNISAR.py" = "mosaicworkflow.autocleanNISAR:main"
cleanoffmerge = "mosaicworkflow.cleanoffmerge:main"
"cleanoffmerge.py" = "mosaicworkflow.cleanoffmerge:main"
updateDateDB = "mosaicworkflow.updateDateDB:main"
"updateDateDB.py" = "mosaicworkflow.updateDateDB:main"
mergeoff = "mosaicworkflow.mergeoff:main"
"mergeoff.py" = "mosaicworkflow.mergeoff:main"
