#!/usr/bin/env python3
"""
cleanoffmerge.py

Run inside an individual offset directory (e.g. track-N/YYYYMMDD_YYYYMMDD_00??/).
Merges fast and slow offsets (if a fast/azimuth.offsets.noclean.fast file is
present), then applies bad-pixel index lists generated by autoclean:

XY mode (default): reads badoffsets_auto.list and removes those pixels from
    both range and azimuth offset arrays.

RA mode: reads badoffsets_auto.list.dr (range) and/or badoffsets_auto.list.da
    (azimuth) and removes each set from its respective component only, leaving
    the other component unaffected.

In both modes, after bad-pixel removal the program:
  - Clips the leading/trailing edge pixels that can produce false matches at
    scene boundaries (fixEdgeEffects).
  - Removes ragged fringe pixels via morphological open (cleanEdges).
  - Fills pin-holes and removes isolated islands via intfloat interpolation
    (islandThreshAndPinHole).

The final cleaned offsets are written back to azimuth.offsets / range.offsets.

RA vs XY mode is selected automatically: if any of the .dr / .da list files
are present the program enters RA mode; otherwise it falls back to XY mode.
"""
import utilities as u
import numpy as np
import scipy.io as io
import os
import xml.etree.ElementTree as ET
from subprocess import call
import argparse
import copy
import scipy.ndimage as morph
import sarfunc as s


def cleanOffMergeUsage():
    print('\033[1m\n Merge fast offsets with regular offsets and then apply '
          'badoffsets_poly.idl, badoffset_auto.idl,and badoffses_auto.float\n')
    print('\tcleanoffmerge -help ')
    print('Notes: ')
    print('\tThis program requires IDL for running mergeoff (could be replaced'
          ' later) \033[0m')
    exit()


def cleanoffmergeArgs():
    ''' Handle command line args'''
    parser = argparse.ArgumentParser(
        description='\033[1mMerge fast offsets with regular offsets and then '
        'apply badoffsets_poly.idl, badoffset_auto.idl, and '
        'badoffsets_auto.float\033[0m',
        epilog='Notes: Ususally called as part of cleanoff process ')
    parser.add_argument('--sensor', type=str, default='S1',
                        help='Sensor (CSK,S1, TSX)')
    parser.add_argument('--tiff', action='store_true', default=False,
                        help='Write the merged/cleaned offsets as GeoTIFF + '
                        'tiff-backed VRT instead of raw binary')
    #
    args = parser.parse_args()
    # log arguments
    #
    return args.sensor, args.tiff


def _getGeoTransform(vrtFile):
    """Parse GeoTransform from a VRT file; return list of 6 floats."""
    tree = ET.parse(vrtFile)
    gt_text = tree.getroot().find('GeoTransform').text
    return [float(v) for v in gt_text.split(',')]


def _writeSingleBandVRT(vrtPath, binFile, nr, na, geoTransform, byteOrder='MSB'):
    """Write a minimal single-band VRT pointing to a raw float32 binary file."""
    lineOffset = nr * 4
    gt = ','.join(f'  {v:.15e}' for v in geoTransform)
    content = (
        f'<VRTDataset rasterXSize="{nr}" rasterYSize="{na}">\n'
        f'  <GeoTransform>{gt}</GeoTransform>\n'
        f'  <VRTRasterBand dataType="Float32" band="1"'
        f' blockXSize="{nr}" blockYSize="1"'
        f' subClass="VRTRawRasterBand">\n'
        f'    <NoDataValue>-2000000000</NoDataValue>\n'
        f'    <SourceFilename relativeToVRT="1">'
        f'{os.path.basename(binFile)}</SourceFilename>\n'
        f'    <ImageOffset>0</ImageOffset>\n'
        f'    <PixelOffset>4</PixelOffset>\n'
        f'    <LineOffset>{lineOffset}</LineOffset>\n'
        f'    <ByteOrder>{byteOrder}</ByteOrder>\n'
        f'  </VRTRasterBand>\n'
        f'</VRTDataset>\n'
    )
    with open(vrtPath, 'w') as fp:
        fp.write(content)


def islandThreshAndPinHole(off, sensorInfo, noDatFiles=False):
    ''' run a copy through interpolator to fill holes and remove
    any islands '''
    holeSize = sensorInfo['normalInterp']['thresh']
    islandThresh = sensorInfo['normalInterp']['islandThresh']
    #
    # make a copy
    offTemp = copy.deepcopy(off)
    # The xxx/yyy intfloat scratch is always raw binary, even in tiff mode -
    # only the final result (written by main) honors the tiff setting.
    offTemp.setTiff(False)
    # read offsets
    offTemp.readSigma()
    print(offTemp.sigmaAFile, off.sigmaRFile, off.datFile)
    # change names to xxx
    offTemp.sigmaFileName(sigmaAFile='xxx.sa', sigmaRFile='xxx.sr')
    offTemp.writeOffsets(fileRoot='xxx.da', rangeFile='xxx.dr',
                         datFile='xxx.dat')
    #
    # run interpolator to produce yyy
    fpStdio, fpStderr = open('xxx.stdio', 'w'), open('xxx.stderr', 'w')
    suffixes = {'.da', '.dr', '.sa', '.sr'}
    if noDatFiles:
        gt = _getGeoTransform(off.vrtFile)
        bo = (off.meta.get('ByteOrder', 'MSB') if off.meta else 'MSB')
        for suffix in suffixes:
            _writeSingleBandVRT(f'xxx{suffix}.vrt', f'xxx{suffix}',
                                off.nr, off.na, gt, bo)
        for suffix in suffixes:
            command = (f'intfloat -inputVRT xxx{suffix}.vrt '
                       f'-outputVRT yyy{suffix}.vrt '
                       f'-wdist -ratThresh 1 '
                       f'-thresh {holeSize} -islandThresh {islandThresh}')
            call(command, shell=True, executable='/bin/csh',
                 stdout=fpStdio, stderr=fpStderr)
            os.remove(f'xxx{suffix}')
            os.remove(f'xxx{suffix}.vrt')
            print(command)
    else:
        for suffix in suffixes:
            command = f'intfloat -wdist -nr {off.nr} -na {off.na} -ratThresh 1 '
            command += f'-thresh {holeSize} -islandThresh {islandThresh} '
            command += f'xxx{suffix} > yyy{suffix}'
            call(command, shell=True, executable='/bin/csh',
                 stdout=fpStdio, stderr=fpStderr)
            os.remove(f'xxx{suffix}')
            print(command)
    #
    # clean up
    fpStdio.close()
    fpStderr.close()
    #
    # read interpolated values to replace originals
    off.verbose = True
    off.readOffsets(fileRoot='yyy.da', rangeFile='yyy.dr',
                    datFile='xxx.da.dat', vrtFile=None)
    # Read directly to avoid issues with vrt vs. dat
    off.azOff = u.readImage('yyy.da', off.nr, off.na, '>f4')
    off.rgOff = u.readImage('yyy.dr', off.nr, off.na, '>f4')
    off.sigmaA = u.readImage('yyy.sa', off.nr, off.na, '>f4')
    off.sigmaR = u.readImage('yyy.sr', off.nr, off.na, '>f4')
    #
    for suffix in {'.da.dat', '.dr.dat', '.stderr', '.stdio', '.dat'}:
        os.remove(f'xxx{suffix}')
    # more cleanup
    for suffix in suffixes:
        os.remove(f'yyy{suffix}')
    if noDatFiles:
        for suffix in suffixes:
            vrtOut = f'yyy{suffix}.vrt'
            if os.path.exists(vrtOut):
                os.remove(vrtOut)
    #
    # make sure file names are correct
    off.setFileRoot('azimuth.offsets')
    off.offsetFileNames(off.fileRoot)
    off.sigmaFileName(sigmaAFile='azimuth.offsets.sa',
                      sigmaRFile='range.offsets.sr')

    # return result
    return off


def cleanEdges(off):
    # mask with data
    mask = np.zeros(off.azOff.shape, dtype=np.byte)
    mask[off.azOff > -2.0e8] = 1
    #
    # opening to kill little jaggies on edges of mask
    kernel1 = np.ones((3, 3), dtype=bool)
    mask1 = morph.binary_dilation(morph.binary_erosion(mask,
                                                       structure=kernel1),
                                  structure=kernel1)
    # these are the jaggie points
    mask[mask1 == 1] = 0
    # u.writeImage('testra.mask', mask, 'u1')
    # now remove them
    off.removeList(np.int32(np.flatnonzero(mask)))
    return off


def fixEdgeEffects(off):
    ''' this takes care of edge effects near near data/no data transitions at
    start and end of images since the sharp transition from data to no data
    can cause a fale match'''
    azIndex = np.arange(0, off.na)
    clip = 4
    cleanMt = len(off.matchType) > 0
    # loop in range
    for i in range(0, off.nr):
        # get good points
        igood = off.azOff[:, i] > -1.9e9
        if np.any(igood):
            # good azimuth indices for this column
            kf = azIndex[igood]
            # get the good min and max
            jmin = np.min(kf)
            jmax = np.max(kf)
            # clip first and last 4
            if jmin < 120:
                off.azOff[0:jmin+clip, i] = -2.0e9
                off.rgOff[0:jmin+clip, i] = -2.0e9
                if cleanMt:
                    off.matchType[0:jmin+clip, i] = 0
            if jmax > (off.na-120):
                off.azOff[jmax-clip:, i] = -2.e9
                off.rgOff[jmax-clip:, i] = -2.e9
                if cleanMt:
                    off.matchType[jmax-clip:, i] = 0
    return off


def main():
    """ This program replaces the former idl cleanoffmerge.pro """
    #
    # process command line
    #
    sensor, tiff = cleanoffmergeArgs()
    sarDef = s.sensorDefinitions(sensor)
    sensorInfo = sarDef.SAR
    #
    # ***** MERGE FAST AND SLOW
    # Save copies of slow offsets and merge with fast
    # assumes the azimuth/range just created
    if os.path.exists('fast/azimuth.offsets.noclean.fast'):
        if not os.path.exists('azimuth.offsets.slow') \
                and not os.path.exists('azimuth.offsets.slow.tif'):
            u.myerror('no slow offsets')
        tiffFlag = ' --tiff' if tiff else ''
        call(f'mergeoff.py {sensor}{tiffFlag}', shell=True,
             executable='/bin/csh')
    #
    # get the offsets, select using vrt or dat files
    verbose = False
    if os.path.exists('offsets.range-azimuth.vrt'):
        off = u.offsets(fileRoot='azimuth.offsets',
                        vrtFile='offsets.range-azimuth.vrt', verbose=verbose,
                        tiff=tiff)
        noDatFiles = True
    else:
        off = u.offsets(fileRoot='azimuth.offsets', verbose=verbose, tiff=tiff)
        noDatFiles = False

    off.getOffsets()

    #
    # filter offsets from hand cleaning
    for badType, badKey in zip(['_poly', '_auto'], ['idel_poly', 'iauto']):
        if os.path.exists(f'badoffsets{badType}.idl'):
            bad = io.readsav(f'badoffsets{badType}.idl')
            try:
                # remove bad points if they exist
                off.removeList(bad[badKey])
            except Exception:
                print(f'no bad points in badoffsets{badType}.idl')
    # remove list from autocull
    # RA mode: per-component lists (.dr → range only, .da → azimuth only)
    if os.path.exists('badoffsets_auto.list.dr') or \
            os.path.exists('badoffsets_auto.list.da'):
        anyRA = False
        if os.path.exists('badoffsets_auto.list.dr'):
            bad = np.fromfile('badoffsets_auto.list.dr', dtype=np.dtype('u4'))
            print('removing ', len(bad), ' autoculled range offsets')
            if len(bad) > 0:
                shapeSave = off.rgOff.shape
                rg = off.rgOff.flatten()
                inRange = np.logical_and(bad >= 0, bad < len(rg))
                rg[bad[inRange]] = -2.e9
                off.rgOff = rg.reshape(shapeSave)
                anyRA = True
        if os.path.exists('badoffsets_auto.list.da'):
            bad = np.fromfile('badoffsets_auto.list.da', dtype=np.dtype('u4'))
            print('removing ', len(bad), ' autoculled azimuth offsets')
            if len(bad) > 0:
                shapeSave = off.azOff.shape
                az = off.azOff.flatten()
                inRange = np.logical_and(bad >= 0, bad < len(az))
                az[bad[inRange]] = -2.e9
                off.azOff = az.reshape(shapeSave)
                anyRA = True
        if anyRA:
            off = fixEdgeEffects(off)
            off = cleanEdges(off)
            off = islandThreshAndPinHole(off, sensorInfo, noDatFiles=noDatFiles)
    # XY mode: single combined list applies to both components
    elif os.path.exists('badoffsets_auto.list'):
        bad = np.fromfile('badoffsets_auto.list', dtype=np.dtype('u4'))
        print('removing ', len(bad), ' autoculled offsets ')
        off.removeList(bad)
        off = fixEdgeEffects(off)
        off = cleanEdges(off)
        off = islandThreshAndPinHole(off, sensorInfo, noDatFiles=noDatFiles)
    #
    # Write the results
    #
    off.offsetFileNames('azimuth.offsets')
    off.writeOffsets(noDatFiles=noDatFiles)


if __name__ == '__main__':
    main()
